[package]
name = "movo"
version = "0.4.1"
edition = "2021"
rust-version = "1.85"
authors = ["sachesi <xsachesi@pm.me>"]
description = "Native GNOME desktop application for movies and series"
license = "GPL-3.0-only"

[lints]
workspace = true

[dependencies]
movo-core = { path = "../movo-core" }

# GTK 4, Libadwaita & Relm4
gtk4 = { version = "0.11", features = ["v4_22"] }
libadwaita = { version = "0.9", features = ["v1_9"] }
relm4 = { version = "0.11", features = ["libadwaita", "gnome_50"] }

# Async runtime & Networking
tokio = { version = "1.43", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }

# System, logging & misc
gettext-rs = { version = "0.8", features = ["gettext-system"] }
image = "0.25"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
serde_json = "1.0"

[lib]
name = "movo"
path = "src/lib.rs"

[[bin]]
name = "movo"
path = "src/main.rs"
